
name: Test
on: [push]

jobs:
  test:
    name: Tests
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,name=iPhone 11']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Run tests
        run: |
          xcodebuild clean test -workspace  AnimalMemoryV2.xcodeproj/project.xcworkspace -scheme AnimalMemoryV2 -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env: 
         destination: ${{ matrix.destination }}
